### ISSUE TITLE
Classpath com diretórios absolutos

### ISSUE THREAD

**Issue by diogomene15** [lucianoedipo/UnoOO#27]
# Classpath com problemas
## Descrição
Reparei que em uma das últimas atualizações do repositório upstream, o professor adicionou os arquivos .jar relacionados ao logger no  arquivo `.classpath`. Contudo, a adição aparentemente foi feita de maneira automática, de modo que os *paths* foram gerados de maneira absoluta:
```xml
<classpathentry kind="lib" path="D:/Luciano/Documentos/GitHub/UnoOO/lib/slf4j-api-2.0.3.jar" sourcepath="libs/slf4j-api-2.0.3-sources.jar"/>
<classpathentry kind="lib" path="D:/Luciano/Documentos/GitHub/UnoOO/lib/slf4j-simple-2.0.3.jar"/>

```
## Pedido de solução
Por favor adicionar os arquivos com um `path` relativo:
### Algo como:
```xml
<classpathentry kind="lib" path="lib/slf4j-api-2.0.3.jar" sourcepath="libs/slf4j-api-2.0.3-sources.jar"/>
<classpathentry kind="lib" path="lib/slf4j-simple-2.0.3.jar"/>
```

**Comment by lucianoedipo** [comment]
Resolvido
